<?php

$banners = array(
    array('1.jpg', 'x'),
    array('2.png', 'pol'),
    array('3.png', 'e'),
    array('4.gif', 'it'),
    array('5.png', 'pol'),
    array('6.png', 'pol'),
    array('7.png', 'b'),
    array('8.png', 'hikky'),
    array('9.png', 'hikky'),
    array('10.png', 'x'),
    array('11.png', 'x'),
    array('12.jpg', 'mus'),
    array('13.png', 'b'),
    array('14.png', 'a'),
    array('15.png', 'b'),
    array('16.jpg', 'b'),
    array('17.png', 'kuv'),
    array('18.png', 'meta'),
    array('19.png', 'a'),
    array('20.png', 'a'),
    array('21.png', 'b'),
    array('22.png', 'e'),
    array('23.jpg', 'b'),
    array('24.png', 'm'),
    array('25.jpg', 'meta'),
    array('26.png', 'h'),
    array('27.jpg', 'b'),
    array('28.png', 'pol'),
    array('29.gif', 'h'),
    array('30.png', 'jp'),
    array('31.png', 'meta'),
    array('32.jpg', 'b'),
    array('33.jpg', 'h'),
    array('34.png', 'e'),
    array('35.jpg', 'jp'),
    array('36.png', 'e'),
    array('37.png', 'h'),
    array('38.jpg', 'b'),
    array('39.jpg', 'it'),
    array('40.jpg', 'b'),
    array('41.png', 'a'),
    array('42.png', 'b'),
    array('43.png', 'pol'),
    array('44.png', 'it'),
    array('45.png', 'meta'),
    array('46.png', 'b'),
    array('47.png', 'b'),
    array('48.jpg', 'e'),
    array('49.gif', 'b'),
    array('50.gif', 'b'),
    array('51.jpg', 'b'),
    array('52.jpg', 'kuv'),
    array('53.gif', 'a'),
    array('54.jpg', 'm'),
    array('55.jpg', 'b'),
    array('56.png', 'b'),
);
$banner = $banners[random_int(0, count($banners) - 1)];

echo <<<EOF
<a href="/$banner[1]/">
    <img src="/banners/$banner[0]" width="480" height="80">
</a>
EOF;
